export const profile = {
  name: "Benjamin Bodin",
  firstName: "BENJAMIN",
  lastName: "BODIN",
  subtitle: "Comédien · Mannequin",
  tagline: "Comédien · Mannequin",
  email: "contact@benjaminbodin.fr",
  instagram: {
    handle: "@_benjaminbodin",
    url: "https://instagram.com/_benjaminbodin",
  },
  website: "www.benjaminbodin.fr",
  showreelUrl: "",
  measurements: {
    "Taille": "176 cm",
    "Poitrine": "86 cm",
    "Tour de taille": "71 cm",
    "Hanches": "85 cm",
    "Entrejambe": "67 cm",
    "Cou": "34 cm",
    "Tour de tête": "56 cm",
    "Veste": "44",
    "Pantalon": "36",
    "Chaussures": "44",
  },
  hair: "Brun",
  eyes: "Marron / Vert",
  ageRange: "25–35 ans",
  languages: ["Français", "Anglais"],
  skills: ["Modeling", "Acting", "High-level Sports"],
  agent: {
    name: "",
    agency: "",
    email: "",
    phone: "",
  },
};
